name: Build Docker images

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [apache, fpm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.image }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/yusufhm/mautic:v4-${{ matrix.image }}
          labels: org.opencontainers.image.source=https://github.com/yusufhm/docker-mautic
